@startuml
title Activity Diagram: Import CV

|Pengguna|
start
:Memilih Import CV;
:Upload PDF;

|Sistem|
:Membaca file;
:Ekstraksi isi CV;
:Form terisi otomatis;

|Pengguna|
:Mengecek hasil;
stop
@enduml
